/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=WorkerBindings apps/worker/src/worker-configuration.d.ts` (hash: 8190611a9dc33268962eef270e001038)
interface __BaseEnv_WorkerBindings {
	ARTIFACTS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	RUNTIME_MODE: "preview";
	OPENAI_MODE: "disabled";
	MEETINGS: DurableObjectNamespace<import("./index").MeetingCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "MeetingCoordinator";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
