/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=WorkerBindings apps/worker/src/worker-configuration.d.ts` (hash: 9d902d4a315fbcd037bb25dc54581b25)
interface __BaseEnv_WorkerBindings {
	ARTIFACTS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	JUDGE_MANAGED_REALTIME_ROUTE_ENABLED: "disabled";
	JUDGE_STRUCTURED_AI_ROUTE_ENABLED: "disabled";
	RUNTIME_MODE: "preview";
	OPENAI_MODE: "disabled";
	OPENAI_MODEL: "gpt-5.6";
	MEETINGS: DurableObjectNamespace<import("./index").MeetingCoordinator>;
	JUDGE_REALTIME_CALLS: DurableObjectNamespace<import("./index").JudgeRealtimeCallController>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "MeetingCoordinator" | "JudgeRealtimeCallController";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
