import { describe, expect, it } from "vitest";

import {
  assertThirdPartyNoticeCurrent,
  collectThirdPartyPackages,
  renderThirdPartyNotices,
} from "../../scripts/generate-third-party-notices.mjs";

describe("third-party notice generation", () => {
  it("classifies direct and transitive packages while ignoring workspace links", () => {
    const packages = collectThirdPartyPackages({
      packages: {
        "": {
          dependencies: { zod: "4.4.3" },
          devDependencies: { vite: "8.1.5" },
        },
        "apps/web": {
          dependencies: { react: "19.2.4" },
        },
        "node_modules/@counterpoint/domain": {
          link: true,
          resolved: "packages/domain",
        },
        "node_modules/react": {
          license: "MIT",
          version: "19.2.4",
        },
        "node_modules/vite": {
          dev: true,
          license: "MIT",
          version: "8.1.5",
        },
        "node_modules/vite/node_modules/picocolors": {
          dev: true,
          license: "ISC",
          version: "1.1.1",
        },
        "node_modules/vite/node_modules/zod": {
          dev: true,
          license: "MIT",
          version: "3.25.76",
        },
        "node_modules/zod": {
          license: "MIT",
          version: "4.4.3",
        },
      },
    });

    expect(packages).toEqual([
      {
        license: "ISC",
        name: "picocolors",
        relationship: "development transitive",
        version: "1.1.1",
      },
      {
        license: "MIT",
        name: "react",
        relationship: "runtime direct",
        version: "19.2.4",
      },
      {
        license: "MIT",
        name: "vite",
        relationship: "development direct",
        version: "8.1.5",
      },
      {
        license: "MIT",
        name: "zod",
        relationship: "development transitive",
        version: "3.25.76",
      },
      {
        license: "MIT",
        name: "zod",
        relationship: "runtime direct",
        version: "4.4.3",
      },
    ]);
  });

  it("fails closed when a third-party package lacks license metadata", () => {
    expect(() =>
      collectThirdPartyPackages({
        packages: {
          "": {},
          "node_modules/unknown": { version: "1.0.0" },
        },
      }),
    ).toThrow("unknown@1.0.0 is missing license metadata");
  });

  it("renders a deterministic generated notice with review-required licenses", () => {
    const notice = renderThirdPartyNotices([
      {
        license: "MIT",
        name: "react",
        relationship: "runtime transitive",
        version: "19.2.4",
      },
      {
        license: "MPL-2.0",
        name: "build-tool",
        relationship: "development transitive",
        version: "1.0.0",
      },
    ]);

    expect(notice).toContain(
      "Generated from `package-lock.json`; do not edit this file manually.",
    );
    expect(notice).toContain(
      "| build-tool | 1.0.0 | MPL-2.0 | development transitive |",
    );
    expect(notice).toContain(
      "Review-required licenses are present only in development dependencies",
    );
  });

  it("rejects a generated notice that is stale relative to the lockfile", () => {
    const lockfile = {
      packages: {
        "": { dependencies: { zod: "4.4.3" } },
        "node_modules/zod": {
          license: "MIT",
          version: "4.4.3",
        },
      },
    };
    const current = renderThirdPartyNotices(
      collectThirdPartyPackages(lockfile),
    );

    expect(() =>
      assertThirdPartyNoticeCurrent(lockfile, current),
    ).not.toThrow();
    expect(() =>
      assertThirdPartyNoticeCurrent(lockfile, `${current}\nstale edit\n`),
    ).toThrow("THIRD_PARTY_NOTICES.md is stale");
  });
});
